project:
  type: website
  output-dir: docs

website:
  title: "humidity-cvd"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: temperature.qmd
        text: Temperature
      - href: humidity.qmd
        text: Humidity

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

