project:
  type: website
  output_dir: docs

website:
  title: "humidity-cvd"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

